language: python
python:
    - "2.7"
cache:
    pip: true
    directories:
    - $HOME/buildout-cache
install:
    - 'pip install -r requirements.txt'
    - 'pip install -r tests/requirements-dev.txt'
    - 'pip install coveralls'
script: 'py.test --cov=screener -n 4 tests/'
after_success: 'coveralls'